IF OBJECT_ID(N'DETAIL_incident') IS NOT NULL
    drop table DETAIL_incident


CREATE TABLE [dbo].[DETAIL_incident](
    --[ID] int not NULL,
    ID INT IDENTITY(1,1) NOT NULL,-- PRIMARY KEY,
    [recid] [char](32) NULL,
    [number] [nvarchar](30) NULL,
    [system] [nvarchar](30) NULL,
    [Company] [nvarchar](100) NULL,
    [Company_ID] INT NULL,
    [businessunit] [nvarchar](100) NULL,
    [isvip] [int] NULL,
    [location] [nvarchar](100) NULL,
    [customer] [nvarchar](100) NULL,
    [subject] [nvarchar](255) NULL,
    [symptom] [nvarchar](255) NULL,
    [priority] [int] NULL,
    [status] [nvarchar](40) NULL,
    [source] [nvarchar](40) NULL,
    [service] [nvarchar](60) NULL,
    [category] [nvarchar](60) NULL,
    [subcategory] [nvarchar](200) NULL,
    [fcr] [int] NULL,
    [fcr_scoped_Format] [int] NULL,
    [fcr_achieved_Format] [int] NULL,
    [ownerteam] [nvarchar](100) NULL,
    [owner_Format] [nvarchar](100) NULL,
    [causecode] [nvarchar](150) NULL,
    [createdby_Format] [nvarchar](100) NULL,
    [createddatetime] [datetime] NULL,
    [createddate_Format] [date] NOT NULL,
    [resolvingteam] [nvarchar](100) NULL,
    [resolvedby_Format] [nvarchar](100) NULL,
    [resolveddatetime] [datetime] NULL,
    [resolveddate_Format] [date] NULL,
    [closedby_Format] [nvarchar](100) NULL,
    [closeddatetime] [datetime] NULL,
    [closeddate_Format] [date] NULL,
    [lastmodby_Format] [nvarchar](100) NULL,
    [lastmoddatetime] [datetime] NULL,
    [lastmoddate_Format] [date] NULL,
    [ResolvedClosedBy_Format] [nvarchar](100) NULL,
    [ResolvedClosedDatetime] [datetime] NULL,
    [ResolvedClosedDate_Format] [date] NULL,
    [breachstatus] [int] NULL,
    [l1dateTime] [datetime] NULL,
    [l1passed] [int] NULL,
    [L2dateTime] [datetime] NULL,
    [l2passed] [int] NULL,
    [l3dateTime] [datetime] NULL,
    [l3passed] [int] NULL,
    [breachdatetime] [datetime] NULL,
    [breachpassed] [int] NULL,
    [targetclockduration] [float] NULL,
    [totalrunningduration] [float] NULL,
    [response_breachpassed] [int] NULL,
    [response_targetclockduration] [float] NULL,
    [response_totalrunningduration] [float] NULL,
    [typeofincident] [nvarchar](20) NULL,
    [reopencount] [int] NULL,
    [reopencount_Flag] [int] NULL,
    [remoteresolution] [int] NULL,
    [resolution] [nvarchar](255) NULL,
    [technicalresolution] [nvarchar](255) NULL,
    [numberofusersaffected] [nvarchar](20) NULL,
    [repeatissue] [int] NULL,
    [breachreason] [nvarchar](255) NULL, 
    [cancellationreason] [nvarchar](255) NULL,    
    [prioritychangecount] [int] NULL,
    [problem_id] [char](32) NULL,
    [parentincident_id] [char](32) NULL
) ON [PRIMARY]
;